# Generated by Django 3.2.9 on 2021-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
