# Generated by Django 3.2.9 on 2021-12-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211211_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
    ]
