# Generated by Django 3.2.9 on 2021-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='link_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
